---

  - name: NVM | Install package
    win_dsc:
      resource_name: cChocoPackageInstaller
      Name: "nvm.portable"
      DependsOn: "[cChocoInstaller]installChoco"
    tags:
      -nvm

  - name: NVM | Install node version
    win_shell: "nvm install {{ nodejs_version }}"
    register: nvm_install_result
    changed_when: "nvm_install_result.stdout|search('Installation complete. If you want to use this version, type')"
    failed_when: "nvm_install_result.stdout|search(' is not available.')"
    tags:
      -nvm

  #  not supported in 1.1.5 yet
  # - name: NVM | alias default
  #   win_shell: "nvm alias default {{ nodejs_version }}"
  #   tags:
  #     -nvm
